---
language: minimal
matrix:
  include:
    - env: TEST=shellcheck
      services:
        - docker
      script: ./tests/shellcheck.sh

    - env: TEST=yamllint
      services:
        - docker
      script: ./tests/yamllint.sh

    - env: TEST=markdownlint
      services:
        - docker
      script: ./tests/mdl.sh

    - env: TEST=jsonlint
      services:
        - docker
      script: ./tests/jsonlint.sh

    - env: TEST=make
      script: ./tests/make.sh
branches:
  only:
    - master
    # also matched against tag pushes
    - /^\d+\.\d+\.\d+$/
notifications:
  email: false
