#!/usr/bin/env bash

set -o errexit

TAG=${TAG:-w_2016_05}
PRODUCTS=${PRODUCTS:-lsst_distrib}

bundle install
bundle exec librarian-puppet install
./bin/packer build --only=docker-centos-6,docker-centos-7 centos_packerprep.json
./bin/packer build --only=docker-centos-6,docker-centos-7 centos_newinstall.json
./bin/packer build --only=docker-centos-6,docker-centos-7 -var tag="$TAG" -var products="$PRODUCTS" centos_build.json
# packer can't set the USER or WORKDIR on a container so we are using trivial
# Dockerfiles that overwrite the short tag name (the one without the timestamp)
# XXX this is non-idempotent
docker build -t "lsstsqre/centos:6-stack-${PRODUCTS}-${TAG}" docker/centos-6/
docker build -t "lsstsqre/centos:7-stack-${PRODUCTS}-${TAG}" docker/centos-7/
docker push "lsstsqre/centos:6-stack-${PRODUCTS}-${TAG}"
docker push "lsstsqre/centos:7-stack-${PRODUCTS}-${TAG}"
