#!/usr/bin/env bash

set -o errexit

TAG=${TAG:-w_2016_05}
PRODUCTS=${PRODUCTS:-lsst_distrib}

print_error() {
    >&2 echo -e "$@"
}

usage() {
    if [[ ! -z "$1" ]]; then
        print_error "$0: $1"
    fi
    print_error
    print_error "Usage: $0 <step>"
    exit 1
}

if [[ $# -eq 0 ]]; then
    usage "<step> option required"
fi

if [[ $# -gt 1 ]]; then
    usage "only one option is allowed"
fi

case $1 in
    packerprep | stackbase | devtoolset | newinstall | build | push)
        STEP=$1
        ;;
    *)
        [[ $# -gt 0 ]] && usage "Unknown option: $1"
        ;;
esac

echo "building step: $STEP"


setup() {
    make
    bundle install
    bundle exec librarian-puppet install
}

case $STEP in
    packerprep)
        setup
        ./bin/packer build --only=docker centos_packerprep.json
        ;;
    stackbase)
        setup
        ./bin/packer build --only=docker centos_stackbase.json
        ;;
    devtoolset)
        setup
        ./bin/packer build --only=docker centos_devtoolset.json
        ;;
    newinstall)
        setup
        ./bin/packer build --only=docker centos_newinstall.json
        ;;
    build)
        setup
        ./bin/packer build --only=docker \
            -var tag="$TAG" \
            -var products="$PRODUCTS" \
            centos_build.json
        ;;
    push)
        docker push "lsstsqre/centos:6-stack-${PRODUCTS}-${TAG}"
        docker push "lsstsqre/centos:7-stack-${PRODUCTS}-${TAG}"
        ;;
esac
